#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  zookeeper0:
    extends:
        file: base.yaml
        service: zookeeper
    container_name: zookeeper0
    environment:
        - ZOO_MY_ID=1
        - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888 

  zookeeper1:
    extends:
        file: base.yaml
        service: zookeeper
    container_name: zookeeper1
    environment:
        - ZOO_MY_ID=2
        - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888 

  zookeeper2:
    extends:
        file: base.yaml
        service: zookeeper
    container_name: zookeeper2
    environment:
        - ZOO_MY_ID=3
        - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888 

  kafka0:
    extends:
        file: base.yaml
        service: kafka
    container_name: kafka0
    environment:
        - KAFKA_BROKER_ID=0
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
        - zookeeper0
        - zookeeper1
        - zookeeper2  

  kafka1:
    extends:
        file: base.yaml
        service: kafka
    container_name: kafka1
    environment:
        - KAFKA_BROKER_ID=1
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
        - zookeeper0
        - zookeeper1
        - zookeeper2

  kafka2:
    extends:
        file: base.yaml
        service: kafka
    container_name: kafka2
    environment:
        - KAFKA_BROKER_ID=2
        - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
        - zookeeper0
        - zookeeper1
        - zookeeper2

  ca.org1.example.com:
    container_name: ca_peerOrg1
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4bb4c70d2ca988981704b5e7daf0dd998cff7d7f13ed0531e480220fcc6beafa_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/4bb4c70d2ca988981704b5e7daf0dd998cff7d7f13ed0531e480220fcc6beafa_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  ca.org2.example.com:
    container_name: ca_peerOrg2
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/66ebd6fd8b4ed3268ce08783be18c9a22a19c51eb4035397f81ceddc5a604f47_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/66ebd6fd8b4ed3268ce08783be18c9a22a19c51eb4035397f81ceddc5a604f47_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./channel/crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config

  orderer0.example.com:
    container_name: orderer0.example.com
    extends:
      file:   base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer0.example.com
    ports:
      - 7050:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/:/etc/hyperledger/crypto/orderer
    depends_on:
      - kafka0
      - kafka1
      - kafka2

  orderer1.example.com:
    container_name: orderer1.example.com
    extends:
      file:   base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer1.example.com
    ports:
      - 8050:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/:/etc/hyperledger/crypto/orderer
    depends_on:
      - kafka0
      - kafka1
      - kafka2 

  orderer2.example.com:
    container_name: orderer2.example.com
    extends:
      file:   base.yaml
      service: orderer-base
    environment:
      - ORDERER_HOST=orderer2.example.com
    ports:
      - 9050:7050
    volumes:
      - ./channel/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/:/etc/hyperledger/crypto/orderer
    depends_on:
      - kafka0
      - kafka1
      - kafka2
  
  couchdb0:
    container_name: couchdb0
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      - COUCHDB_USER=peer0org1
      - COUCHDB_PASSWORD=nothingcomples@123
    ports:
      - "7984:5984"

  couchdb1:
    container_name: couchdb1
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      - COUCHDB_USER=peer1org1
      - COUCHDB_PASSWORD=nothingcomples@123
    ports:
      - "8984:5984"

  couchdb2:
    container_name: couchdb2
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      - COUCHDB_USER=peer0org2
      - COUCHDB_PASSWORD=nothingcomples@123
    ports:
      - "9984:5984"

  couchdb3:
    container_name: couchdb3
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      - COUCHDB_USER=peer1org2
      - COUCHDB_PASSWORD=nothingcomples@123
    ports:
      - "10984:5984"

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0org1
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomples@123
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer0.example.com
      - orderer1.example.com
      - orderer2.example.com      
      - couchdb0

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1org1
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomples@123
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
      - ./channel/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer0.example.com
      - orderer1.example.com
      - orderer2.example.com      
      - couchdb1

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer0.org2.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb2:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0org2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomples@123
    ports:
      - 8051:7051
      - 8053:7053
    volumes:
      - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer0.example.com
      - orderer1.example.com
      - orderer2.example.com 
      - couchdb2

  peer1.org2.example.com:
    container_name: peer1.org2.example.com
    extends:
      file:   base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org2.example.com
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_ADDRESS=peer1.org2.example.com:7051

      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1org2
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=nothingcomples@123
    ports:
      - 8056:7051
      - 8058:7053
    volumes:
      - ./channel/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/:/etc/hyperledger/crypto/peer
    depends_on:
      - orderer0.example.com
      - orderer1.example.com
      - orderer2.example.com 
      - couchdb3