# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
    privnet:

services:

    orderer0.example.com:
        extends:
            file: ../base/docker-compose-base.yaml
            service: orderer
        container_name: orderer0.example.com
        environment:
            - ORDERER_GENERAL_GENESISPROFILE=SampleSingleMSPSolo
            - ORDERER_HOST=orderer0.example.com
        volumes:
            - ../../artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp:/var/hyperledger/msp
            - ../../artifacts/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/tls:/var/hyperledger/tls
        networks:
          - privnet
        ports:
          - 7050:7050

    peer0.org1.example.com:
        extends:
            file: ../base/docker-compose-base.yaml
            service: peer
        container_name: peer0.org1.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org1.example.com:7052
            - CORE_PEER_ID=peer0.org1.example.com
            - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org1.example.com:7051
            # Set this peer as an anchor peer in configtx.yaml
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG1}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG1}
            - CORE_PEER_LOCALMSPID=org1.example.com
        volumes:
            - ../../artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/var/hyperledger/msp
            - ../../artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/var/hyperledger/tls
        depends_on:
            - orderer0.example.com
        networks:
          - privnet
        ports:
          - 7051:7051
          - 7053:7053

    peer0.org2.example.com:
        extends:
            file: ../base/docker-compose-base.yaml
            service: peer
        container_name: peer0.org2.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org2.example.com:7052
            - CORE_PEER_ID=peer0.org2.example.com
            - CORE_PEER_ADDRESS=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.org2.example.com:7051
            # Set this peer as an anchor peer in configtx.yaml
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER0_ORG2}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER0_ORG2}
            - CORE_PEER_LOCALMSPID=org2.example.com
        volumes:
            - ../../artifacts/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp:/var/hyperledger/msp
            - ../../artifacts/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls:/var/hyperledger/tls
        depends_on:
            - orderer0.example.com
            - peer0.org1.example.com
        networks:
          - privnet
        ports:
          - 9051:7051
          - 9053:7053

    peer1.org1.example.com:
        extends:
            file: ../base/docker-compose-base.yaml
            service: peer
        container_name: peer1.org1.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org1.example.com:7052
            - CORE_PEER_ID=peer1.org1.example.com
            - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER1_ORG1}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER1_ORG1}
            - CORE_PEER_LOCALMSPID=org1.example.com
        volumes:
            - ../../artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/var/hyperledger/msp
            - ../../artifacts/crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/var/hyperledger/tls
        depends_on:
            - orderer0.example.com
            - peer0.org1.example.com
        networks:
          - privnet
        ports:
          - 8051:7051
          - 8053:7053

    peer1.org2.example.com:
        extends:
            file: ../base/docker-compose-base.yaml
            service: peer
        container_name: peer1.org2.example.com
        environment:
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org2.example.com:7052
            - CORE_PEER_ID=peer1.org2.example.com
            - CORE_PEER_ADDRESS=peer1.org2.example.com:7051
            - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org2.example.com:7051
            - CORE_PEER_GOSSIP_ORGLEADER=${CORE_PEER_GOSSIP_ORGLEADER_PEER1_ORG2}
            - CORE_PEER_GOSSIP_USELEADERELECTION=${CORE_PEER_GOSSIP_USELEADERELECTION_PEER1_ORG2}
            - CORE_PEER_LOCALMSPID=org2.example.com
        volumes:
            - ../../artifacts/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/msp:/var/hyperledger/msp
            - ../../artifacts/crypto-config/peerOrganizations/org2.example.com/peers/peer1.org2.example.com/tls:/var/hyperledger/tls
        depends_on:
            - orderer0.example.com
            - peer0.org2.example.com
        networks:
          - privnet
        ports:
          - 10051:7051
          - 10053:7053
